### ISSUE TITLE
[BUG] Bug report Checksum Inconsistency

### ISSUE THREAD

**Issue by Supakurr** [ModShardTeam/ModShardLauncher#87]
## **Describe the Bug :**
Followed all the steps from the tutorial until I had to load the vanilla.win file. 
The Console puts out the following Message:

"[19:37:04 INF] Launching msl {v0.12.1.0}
[19:37:04 INF] Reading {AutoPathfinder} built with version {v0.11.2.0}
[19:37:09 WRN] Checksum inconsistency, {C:\Program Files (x86)\Steam\steamapps\common\Stoneshard\vanilla.win} is not vanilla.
[19:37:14 INF] Successfully load: C:\Program Files (x86)\Steam\steamapps\common\Stoneshard\vanilla.win.
[19:37:14 ERR] Something went wrong
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at ModShardLauncher.ModLoader.GetTable(String name)
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at ModShardLauncher.ModLoader.GetTable(String name)
   at ModShardLauncher.ModLoader.Initalize()
   at ModShardLauncher.DataLoader.LoadFile(String filename, Boolean re)
   at ModShardLauncher.DataLoader.DoOpenDialog()
   at ModShardLauncher.Controls.ModInfos.Open_Click(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at ModShardLauncher.App.Main()"
and then shuts down closing MSL.
I tried moving the Stoneshard folder to another drive, I tried to load the game file without mods, but the message repeats itself starting with "Checksum inconsistency" and after a few seconds puts out the rest of the error message.

## **Steps To Reproduce :**
unknown since the tutorial has been followed step by step.

## **Expected Behavior :**
It's supposed to load the profile and then I should be able to enable/disable the mods.

## **Screenshots if applicable :**
...

---

## **Additional Information :**
- Stoneshard Version : **0.9.1.0**
- MSL Version : **v.0.12.1**
- .NET 6.0 is also installed

## **Additional Context :**
My Guess is that it could be an error due to the recent update today, but I'm open for any suggestions.

**Comment by RelativeSpade** [comment]
I'm not a contributor, but I took a look, and the reason as to why this occurs appears to be because they changed "gml_GlobalScript_table_weapons" to "gml_Script_table_weapons" and _possibly_ removed "gml_GlobalScript_table_weapons_text" (it doesn't exactly make sense, but I can't find it in the data.win)

**Comment by RelativeSpade** [comment]
Correction, it appears gml_Script_table_weapons was in past versions as well, they have removed "gml_GlobalScript_table_weapons" and "gml_GlobalScript_table_weapons_text"

**Comment by filipszewczyk99** [comment]
I'm also facing this issue

**Comment by haysnaidra31** [comment]
I'm also having this problem, hopefully there will be a solution soon.

**Comment by jkripak** [comment]
I also have this issue

**Comment by g-192** [comment]
So I tried debugging this and the issue seems to be Data.Code which returns null. 

When you open data.win with the  UnderTaleModTool it says in a notice that the code has been moved to the Stoneshard.exe file. 

I thought maybe we could ignore the code resource as long as mods don't touch that but replacing Line 57 in the ModLoader.cs with ``UndertaleCode table = new UndertaleCode();´´ (just so that the rest of the code runs) did not temporarly fix it since the decompiler does not accept it (could't figure out why).  

I am out of ideas if someone has something I could try again but reading out the .exe for the code resource might be too much for me.

**Comment by RelativeSpade** [comment]
They switched compilers from VM to YCC, so the code is now baked into the exe; because this tool is based on the UnderTaleModTool, it would need some major changes to be compatible with the new exe. There are tools out there for reading and writing YCC already; however, it would still require a significant rewrite to make the change.

**Comment by g-192** [comment]
Yeah but we could just ignore everything releated to code and skip it as a workaround. 

Only mods that touch code would be impacted which is atleast something, right?

**Comment by RelativeSpade** [comment]
That would require some playing around to see. However, I am of the opinion that such a workaround is practically useless regardless of whether it would actually work or not because most mods need to use some form of code.

**Comment by g-192** [comment]
Which tools did you have in mind for reading and writing YCC and are they compatible with C#. 

I might try to see if I can do it.

**Comment by s71m** [comment]
vote for fix this bug

**Comment by Nylux** [comment]
This issue was caused by using MSL before the VM versions were released.

The checksum inconsistency is a simple warning, as we're keeping a whitelist of supported versions.
It doesn't prevent the use of MSL whatsoever though, so no worries there.
