### ISSUE TITLE
[BUG] Bug report

### ISSUE THREAD

**Issue by nakiriayatoki** [ModShardTeam/ModShardLauncher#89]
## **Describe the Bug :**
...Quitting without warning when opening a .win file

## **Steps To Reproduce :**
...

## **Expected Behavior :**
...

## **Screenshots if applicable :**
_You can directly paste screenshots here, no need for external hosting._
...

---

## **Additional Information :**
- Stoneshard Version : **X.X.X.X**
- MSL Version : **X.X.X.X**

## **Additional Context :**
_Add any other context about the problem here._
...

**Comment by ZleZlo** [comment]
Hi, 
Have same issue.
Message in logs:
```
2024-12-21 16:23:20.392 +01:00 [INF] Reading {Rusty_InvExt} built with version v0.12.1.0
2024-12-21 16:24:19.601 +01:00 [INF] Successfully load: E:\Games\Stoneshard\vanila.win.
2024-12-21 16:24:19.607 +01:00 [ERR] Something went wrong
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at ModShardLauncher.ModLoader.GetTable(String name)
```
AFIU I am using version v0.12.1.0
My guess will be that Launcher no longer work with latest version of the game.
I am running latest GOG version of the game (Beta 0.9.1.7).

**Comment by quasiperfect** [comment]
hi
same here

**Comment by Nylux** [comment]
This issue was caused by using MSL before the VM versions were released.
